DATE_DEBIAN="20221219"
DATE_UBUNTU="20221130"
VERSION_bookworm="bookworm-${DATE_DEBIAN}"
VERSION_bullseye="bullseye-${DATE_DEBIAN}"
VERSION_buster="buster-${DATE_DEBIAN}"
VERSION_jammy="jammy-${DATE_UBUNTU}"
VERSION_focal="focal-${DATE_UBUNTU}"
VERSION_bionic="bionic-${DATE_UBUNTU}"

VERSIONS="bookworm/debian:${VERSION_bookworm} bullseye/debian:${VERSION_bullseye} buster/debian:${VERSION_buster} jammy/ubuntu:${VERSION_jammy} focal/ubuntu:${VERSION_focal} bionic/ubuntu:${VERSION_bionic}"
