DATE_DEBIAN="20240110"
VERSION_trixie="trixie-${DATE_DEBIAN}"
VERSION_bookworm="bookworm-${DATE_DEBIAN}"
VERSION_bullseye="bullseye-${DATE_DEBIAN}"
VERSION_buster="buster-${DATE_DEBIAN}"
VERSION_noble="noble-20240114"
VERSION_jammy="jammy-20240111"
VERSION_focal="focal-20231211"

VERSIONS="trixie/debian:${VERSION_trixie} bookworm/debian:${VERSION_bookworm} bullseye/debian:${VERSION_bullseye} buster/debian:${VERSION_buster} noble/ubuntu:${VERSION_noble} jammy/ubuntu:${VERSION_jammy} focal/ubuntu:${VERSION_focal}"
